---
title: "Analysis of Average Working Hours and GDP around the world from 1970 - 2017"
author: "GROUP 02 (Zhenyu Wu - Harsh Katiyar - Liwen Pan - Josephine Valensia)"
date: '2022-05-24'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: css/style.css
    yolo: FALSE
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```



```{r read_data, echo=FALSE, message=FALSE, warning=FALSE}
Analysis_Data <- read_csv(here::here("Data/Assignment_data.csv"))
```

class: left, top

# CONTENTS



1. Introduction (Repo Stucture & Research Question)

2. Section 1 (China & US)

3. Section 2 (Indua & UK)

4. Section 3 (French & Italy)

5. Section 4 (Australia & Indonesia)

6. Conclusion

---

class: left, top

### Section 4 Australia & Indonesia
##### Countries Background

```{r au_idn, echo=FALSE}
au_idn <- Analysis_Data %>%
  rename(Country = "Entity", 
         avh = "Average annual hours worked by persons engaged (avh) (PWT 9.1 (2019))",
         gdp = "Output-side real GDP per capita (gdppc_o) (PWT 9.1 (2019))") %>%
  select(Country, Year, avh, gdp) %>%
  filter(Country %in% c("Australia", "Indonesia"), 
         Year >=1970 & Year <=2017)
```

.pull-left[
```{r avh, echo=FALSE}
au_idn %>% 
  ggplot(aes(x = Year, 
             y = avh, 
             color = Country)) +
  geom_line(show.legend = FALSE) +
    labs(x = "Year",
         y = "hours",
         title = "Average annual hours worked by workers from year 1970-2017") +
  scale_y_continuous(labels = label_number(big.mark = ","))
  
```
]

.pull-right[
```{r gdp, echo=FALSE}
au_idn %>% 
  ggplot(aes(x = Year, 
             y = gdp, 
             color = Country)) +
  geom_line()+
    labs(x = "Year",
         y = "USD",
         title = "GDP per capita from year 1970-2017",
         ) +
  scale_y_continuous(labels = label_number(prefix="$", big.mark = ","))
  
```
]

---

```{r endslide, child="EndSlide/endslide.Rmd"}
```  

